# Generated by Django 5.2.7 on 2025-10-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('icon', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('translated_languages', models.JSONField(default=list)),
                ('settings', models.JSONField(blank=True, null=True)),
                ('banners', models.JSONField(blank=True, default=list, null=True)),
                ('promotional_sliders', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'db_table': 'type',
            },
        ),
    ]
