# Generated by Django 5.2.7 on 2025-10-10 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(max_length=20)),
                ('image', models.JSONField(blank=True, null=True)),
                ('translated_languages', models.JSONField(blank=True, default=list)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='product.type')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('icon', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.type')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, max_length=20, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('simple', 'Simple'), ('variable', 'Variable'), ('digital', 'Digital')], db_index=True, max_length=20, null=True)),
                ('price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('sku', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.JSONField(blank=True, null=True)),
                ('gallery', models.JSONField(blank=True, default=list, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='product.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.type')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='product.tag')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
