# Generated by Django 5.2.7 on 2025-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('language', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], db_index=True, max_length=20)),
                ('amount', models.FloatField()),
                ('minimum_cart_amount', models.FloatField()),
                ('active_from', models.DateTimeField()),
                ('expire_at', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=False)),
                ('translated_languages', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
    ]
