# Generated by Django 5.2.7 on 2025-10-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(20, 'ADMIN'), (5, 'GUEST')], default=5),
        ),
    ]
