# Generated by Django 5.2.7 on 2025-10-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(20, 'ADMIN'), (10, 'CUSTOMER'), (5, 'GUEST')], default=5),
        ),
    ]
